// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GameAccountColumns holds the columns for the "game_account" table.
	GameAccountColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "user_account", Type: field.TypeString, Nullable: true, Size: 100, Comment: "用户账号"},
		{Name: "credential", Type: field.TypeString, Nullable: true, Size: 255, Comment: "用户登录凭证"},
		{Name: "start_time", Type: field.TypeTime, Nullable: true, Comment: "开始时间"},
		{Name: "expire_time", Type: field.TypeTime, Nullable: true, Comment: "过期时间"},
		{Name: "type", Type: field.TypeInt32, Nullable: true, Comment: "游戏类型"},
		{Name: "enabled", Type: field.TypeBool, Comment: "是否启用", Default: false},
		{Name: "emulator_id", Type: field.TypeInt64, Nullable: true, Comment: "分配的模拟器ID"},
	}
	// GameAccountTable holds the schema information for the "game_account" table.
	GameAccountTable = &schema.Table{
		Name:       "game_account",
		Comment:    "游戏账号表",
		Columns:    GameAccountColumns,
		PrimaryKey: []*schema.Column{GameAccountColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_game_account_tenant_user_account",
				Unique:  true,
				Columns: []*schema.Column{GameAccountColumns[7], GameAccountColumns[8]},
			},
			{
				Name:    "idx_game_account_tenant_type",
				Unique:  false,
				Columns: []*schema.Column{GameAccountColumns[7], GameAccountColumns[12]},
			},
			{
				Name:    "idx_game_account_tenant_enabled",
				Unique:  false,
				Columns: []*schema.Column{GameAccountColumns[7], GameAccountColumns[13]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GameAccountTable,
	}
)

func init() {
	GameAccountTable.Annotation = &entsql.Annotation{
		Table:     "game_account",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
}
