// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"
	"go-wind-admin/app/game/service/internal/data/ent/gameaccount"
	"go-wind-admin/app/game/service/internal/data/ent/schema"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	gameaccountMixin := schema.GameAccount{}.Mixin()
	gameaccount.Policy = privacy.NewPolicies(gameaccountMixin[3], schema.GameAccount{})
	gameaccount.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := gameaccount.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	gameaccountMixinFields0 := gameaccountMixin[0].Fields()
	_ = gameaccountMixinFields0
	gameaccountMixinFields3 := gameaccountMixin[3].Fields()
	_ = gameaccountMixinFields3
	gameaccountFields := schema.GameAccount{}.Fields()
	_ = gameaccountFields
	// gameaccountDescTenantID is the schema descriptor for tenant_id field.
	gameaccountDescTenantID := gameaccountMixinFields3[0].Descriptor()
	// gameaccount.DefaultTenantID holds the default value on creation for the tenant_id field.
	gameaccount.DefaultTenantID = gameaccountDescTenantID.Default.(uint32)
	// gameaccountDescUserAccount is the schema descriptor for user_account field.
	gameaccountDescUserAccount := gameaccountFields[0].Descriptor()
	// gameaccount.UserAccountValidator is a validator for the "user_account" field. It is called by the builders before save.
	gameaccount.UserAccountValidator = gameaccountDescUserAccount.Validators[0].(func(string) error)
	// gameaccountDescCredential is the schema descriptor for credential field.
	gameaccountDescCredential := gameaccountFields[1].Descriptor()
	// gameaccount.CredentialValidator is a validator for the "credential" field. It is called by the builders before save.
	gameaccount.CredentialValidator = gameaccountDescCredential.Validators[0].(func(string) error)
	// gameaccountDescEnabled is the schema descriptor for enabled field.
	gameaccountDescEnabled := gameaccountFields[5].Descriptor()
	// gameaccount.DefaultEnabled holds the default value on creation for the enabled field.
	gameaccount.DefaultEnabled = gameaccountDescEnabled.Default.(bool)
	// gameaccountDescID is the schema descriptor for id field.
	gameaccountDescID := gameaccountMixinFields0[0].Descriptor()
	// gameaccount.IDValidator is a validator for the "id" field. It is called by the builders before save.
	gameaccount.IDValidator = gameaccountDescID.Validators[0].(func(uint32) error)
}

const (
	Version = "v0.14.6"                                         // Version of ent codegen.
	Sum     = "h1:/f2696BpwuWAEEG6PVGWflg6+Inrpq4pRWuNlWz/Skk=" // Sum of ent codegen.
)
