// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-wind-admin/app/game/service/internal/data/ent/gameaccount"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 1)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   gameaccount.Table,
			Columns: gameaccount.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint32,
				Column: gameaccount.FieldID,
			},
		},
		Type: "GameAccount",
		Fields: map[string]*sqlgraph.FieldSpec{
			gameaccount.FieldCreatedBy:   {Type: field.TypeUint32, Column: gameaccount.FieldCreatedBy},
			gameaccount.FieldUpdatedBy:   {Type: field.TypeUint32, Column: gameaccount.FieldUpdatedBy},
			gameaccount.FieldDeletedBy:   {Type: field.TypeUint32, Column: gameaccount.FieldDeletedBy},
			gameaccount.FieldCreatedAt:   {Type: field.TypeTime, Column: gameaccount.FieldCreatedAt},
			gameaccount.FieldUpdatedAt:   {Type: field.TypeTime, Column: gameaccount.FieldUpdatedAt},
			gameaccount.FieldDeletedAt:   {Type: field.TypeTime, Column: gameaccount.FieldDeletedAt},
			gameaccount.FieldTenantID:    {Type: field.TypeUint32, Column: gameaccount.FieldTenantID},
			gameaccount.FieldUserAccount: {Type: field.TypeString, Column: gameaccount.FieldUserAccount},
			gameaccount.FieldCredential:  {Type: field.TypeString, Column: gameaccount.FieldCredential},
			gameaccount.FieldStartTime:   {Type: field.TypeTime, Column: gameaccount.FieldStartTime},
			gameaccount.FieldExpireTime:  {Type: field.TypeTime, Column: gameaccount.FieldExpireTime},
			gameaccount.FieldType:        {Type: field.TypeInt32, Column: gameaccount.FieldType},
			gameaccount.FieldEnabled:     {Type: field.TypeBool, Column: gameaccount.FieldEnabled},
			gameaccount.FieldEmulatorID:  {Type: field.TypeInt64, Column: gameaccount.FieldEmulatorID},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *GameAccountQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the GameAccountQuery builder.
func (_q *GameAccountQuery) Filter() *GameAccountFilter {
	return &GameAccountFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *GameAccountMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the GameAccountMutation builder.
func (m *GameAccountMutation) Filter() *GameAccountFilter {
	return &GameAccountFilter{config: m.config, predicateAdder: m}
}

// GameAccountFilter provides a generic filtering capability at runtime for GameAccountQuery.
type GameAccountFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *GameAccountFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql uint32 predicate on the id field.
func (f *GameAccountFilter) WhereID(p entql.Uint32P) {
	f.Where(p.Field(gameaccount.FieldID))
}

// WhereCreatedBy applies the entql uint32 predicate on the created_by field.
func (f *GameAccountFilter) WhereCreatedBy(p entql.Uint32P) {
	f.Where(p.Field(gameaccount.FieldCreatedBy))
}

// WhereUpdatedBy applies the entql uint32 predicate on the updated_by field.
func (f *GameAccountFilter) WhereUpdatedBy(p entql.Uint32P) {
	f.Where(p.Field(gameaccount.FieldUpdatedBy))
}

// WhereDeletedBy applies the entql uint32 predicate on the deleted_by field.
func (f *GameAccountFilter) WhereDeletedBy(p entql.Uint32P) {
	f.Where(p.Field(gameaccount.FieldDeletedBy))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *GameAccountFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(gameaccount.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *GameAccountFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(gameaccount.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *GameAccountFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(gameaccount.FieldDeletedAt))
}

// WhereTenantID applies the entql uint32 predicate on the tenant_id field.
func (f *GameAccountFilter) WhereTenantID(p entql.Uint32P) {
	f.Where(p.Field(gameaccount.FieldTenantID))
}

// WhereUserAccount applies the entql string predicate on the user_account field.
func (f *GameAccountFilter) WhereUserAccount(p entql.StringP) {
	f.Where(p.Field(gameaccount.FieldUserAccount))
}

// WhereCredential applies the entql string predicate on the credential field.
func (f *GameAccountFilter) WhereCredential(p entql.StringP) {
	f.Where(p.Field(gameaccount.FieldCredential))
}

// WhereStartTime applies the entql time.Time predicate on the start_time field.
func (f *GameAccountFilter) WhereStartTime(p entql.TimeP) {
	f.Where(p.Field(gameaccount.FieldStartTime))
}

// WhereExpireTime applies the entql time.Time predicate on the expire_time field.
func (f *GameAccountFilter) WhereExpireTime(p entql.TimeP) {
	f.Where(p.Field(gameaccount.FieldExpireTime))
}

// WhereType applies the entql int32 predicate on the type field.
func (f *GameAccountFilter) WhereType(p entql.Int32P) {
	f.Where(p.Field(gameaccount.FieldType))
}

// WhereEnabled applies the entql bool predicate on the enabled field.
func (f *GameAccountFilter) WhereEnabled(p entql.BoolP) {
	f.Where(p.Field(gameaccount.FieldEnabled))
}

// WhereEmulatorID applies the entql int64 predicate on the emulator_id field.
func (f *GameAccountFilter) WhereEmulatorID(p entql.Int64P) {
	f.Where(p.Field(gameaccount.FieldEmulatorID))
}
