// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-wind-admin/app/game/service/internal/data/ent/gameaccount"
	"go-wind-admin/app/game/service/internal/data/ent/predicate"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeGameAccount = "GameAccount"
)

// GameAccountMutation represents an operation that mutates the GameAccount nodes in the graph.
type GameAccountMutation struct {
	config
	op             Op
	typ            string
	id             *uint32
	created_by     *uint32
	addcreated_by  *int32
	updated_by     *uint32
	addupdated_by  *int32
	deleted_by     *uint32
	adddeleted_by  *int32
	created_at     *time.Time
	updated_at     *time.Time
	deleted_at     *time.Time
	tenant_id      *uint32
	addtenant_id   *int32
	user_account   *string
	credential     *string
	start_time     *time.Time
	expire_time    *time.Time
	_type          *int32
	add_type       *int32
	enabled        *bool
	emulator_id    *int64
	addemulator_id *int64
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*GameAccount, error)
	predicates     []predicate.GameAccount
}

var _ ent.Mutation = (*GameAccountMutation)(nil)

// gameaccountOption allows management of the mutation configuration using functional options.
type gameaccountOption func(*GameAccountMutation)

// newGameAccountMutation creates new mutation for the GameAccount entity.
func newGameAccountMutation(c config, op Op, opts ...gameaccountOption) *GameAccountMutation {
	m := &GameAccountMutation{
		config:        c,
		op:            op,
		typ:           TypeGameAccount,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withGameAccountID sets the ID field of the mutation.
func withGameAccountID(id uint32) gameaccountOption {
	return func(m *GameAccountMutation) {
		var (
			err   error
			once  sync.Once
			value *GameAccount
		)
		m.oldValue = func(ctx context.Context) (*GameAccount, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().GameAccount.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withGameAccount sets the old GameAccount of the mutation.
func withGameAccount(node *GameAccount) gameaccountOption {
	return func(m *GameAccountMutation) {
		m.oldValue = func(context.Context) (*GameAccount, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m GameAccountMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m GameAccountMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of GameAccount entities.
func (m *GameAccountMutation) SetID(id uint32) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *GameAccountMutation) ID() (id uint32, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *GameAccountMutation) IDs(ctx context.Context) ([]uint32, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []uint32{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().GameAccount.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedBy sets the "created_by" field.
func (m *GameAccountMutation) SetCreatedBy(u uint32) {
	m.created_by = &u
	m.addcreated_by = nil
}

// CreatedBy returns the value of the "created_by" field in the mutation.
func (m *GameAccountMutation) CreatedBy() (r uint32, exists bool) {
	v := m.created_by
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedBy returns the old "created_by" field's value of the GameAccount entity.
// If the GameAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GameAccountMutation) OldCreatedBy(ctx context.Context) (v *uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedBy: %w", err)
	}
	return oldValue.CreatedBy, nil
}

// AddCreatedBy adds u to the "created_by" field.
func (m *GameAccountMutation) AddCreatedBy(u int32) {
	if m.addcreated_by != nil {
		*m.addcreated_by += u
	} else {
		m.addcreated_by = &u
	}
}

// AddedCreatedBy returns the value that was added to the "created_by" field in this mutation.
func (m *GameAccountMutation) AddedCreatedBy() (r int32, exists bool) {
	v := m.addcreated_by
	if v == nil {
		return
	}
	return *v, true
}

// ClearCreatedBy clears the value of the "created_by" field.
func (m *GameAccountMutation) ClearCreatedBy() {
	m.created_by = nil
	m.addcreated_by = nil
	m.clearedFields[gameaccount.FieldCreatedBy] = struct{}{}
}

// CreatedByCleared returns if the "created_by" field was cleared in this mutation.
func (m *GameAccountMutation) CreatedByCleared() bool {
	_, ok := m.clearedFields[gameaccount.FieldCreatedBy]
	return ok
}

// ResetCreatedBy resets all changes to the "created_by" field.
func (m *GameAccountMutation) ResetCreatedBy() {
	m.created_by = nil
	m.addcreated_by = nil
	delete(m.clearedFields, gameaccount.FieldCreatedBy)
}

// SetUpdatedBy sets the "updated_by" field.
func (m *GameAccountMutation) SetUpdatedBy(u uint32) {
	m.updated_by = &u
	m.addupdated_by = nil
}

// UpdatedBy returns the value of the "updated_by" field in the mutation.
func (m *GameAccountMutation) UpdatedBy() (r uint32, exists bool) {
	v := m.updated_by
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedBy returns the old "updated_by" field's value of the GameAccount entity.
// If the GameAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GameAccountMutation) OldUpdatedBy(ctx context.Context) (v *uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedBy: %w", err)
	}
	return oldValue.UpdatedBy, nil
}

// AddUpdatedBy adds u to the "updated_by" field.
func (m *GameAccountMutation) AddUpdatedBy(u int32) {
	if m.addupdated_by != nil {
		*m.addupdated_by += u
	} else {
		m.addupdated_by = &u
	}
}

// AddedUpdatedBy returns the value that was added to the "updated_by" field in this mutation.
func (m *GameAccountMutation) AddedUpdatedBy() (r int32, exists bool) {
	v := m.addupdated_by
	if v == nil {
		return
	}
	return *v, true
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (m *GameAccountMutation) ClearUpdatedBy() {
	m.updated_by = nil
	m.addupdated_by = nil
	m.clearedFields[gameaccount.FieldUpdatedBy] = struct{}{}
}

// UpdatedByCleared returns if the "updated_by" field was cleared in this mutation.
func (m *GameAccountMutation) UpdatedByCleared() bool {
	_, ok := m.clearedFields[gameaccount.FieldUpdatedBy]
	return ok
}

// ResetUpdatedBy resets all changes to the "updated_by" field.
func (m *GameAccountMutation) ResetUpdatedBy() {
	m.updated_by = nil
	m.addupdated_by = nil
	delete(m.clearedFields, gameaccount.FieldUpdatedBy)
}

// SetDeletedBy sets the "deleted_by" field.
func (m *GameAccountMutation) SetDeletedBy(u uint32) {
	m.deleted_by = &u
	m.adddeleted_by = nil
}

// DeletedBy returns the value of the "deleted_by" field in the mutation.
func (m *GameAccountMutation) DeletedBy() (r uint32, exists bool) {
	v := m.deleted_by
	if v == nil {
		return
	}
	return *v, true
}

// OldDeletedBy returns the old "deleted_by" field's value of the GameAccount entity.
// If the GameAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GameAccountMutation) OldDeletedBy(ctx context.Context) (v *uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeletedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeletedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeletedBy: %w", err)
	}
	return oldValue.DeletedBy, nil
}

// AddDeletedBy adds u to the "deleted_by" field.
func (m *GameAccountMutation) AddDeletedBy(u int32) {
	if m.adddeleted_by != nil {
		*m.adddeleted_by += u
	} else {
		m.adddeleted_by = &u
	}
}

// AddedDeletedBy returns the value that was added to the "deleted_by" field in this mutation.
func (m *GameAccountMutation) AddedDeletedBy() (r int32, exists bool) {
	v := m.adddeleted_by
	if v == nil {
		return
	}
	return *v, true
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (m *GameAccountMutation) ClearDeletedBy() {
	m.deleted_by = nil
	m.adddeleted_by = nil
	m.clearedFields[gameaccount.FieldDeletedBy] = struct{}{}
}

// DeletedByCleared returns if the "deleted_by" field was cleared in this mutation.
func (m *GameAccountMutation) DeletedByCleared() bool {
	_, ok := m.clearedFields[gameaccount.FieldDeletedBy]
	return ok
}

// ResetDeletedBy resets all changes to the "deleted_by" field.
func (m *GameAccountMutation) ResetDeletedBy() {
	m.deleted_by = nil
	m.adddeleted_by = nil
	delete(m.clearedFields, gameaccount.FieldDeletedBy)
}

// SetCreatedAt sets the "created_at" field.
func (m *GameAccountMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *GameAccountMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the GameAccount entity.
// If the GameAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GameAccountMutation) OldCreatedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ClearCreatedAt clears the value of the "created_at" field.
func (m *GameAccountMutation) ClearCreatedAt() {
	m.created_at = nil
	m.clearedFields[gameaccount.FieldCreatedAt] = struct{}{}
}

// CreatedAtCleared returns if the "created_at" field was cleared in this mutation.
func (m *GameAccountMutation) CreatedAtCleared() bool {
	_, ok := m.clearedFields[gameaccount.FieldCreatedAt]
	return ok
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *GameAccountMutation) ResetCreatedAt() {
	m.created_at = nil
	delete(m.clearedFields, gameaccount.FieldCreatedAt)
}

// SetUpdatedAt sets the "updated_at" field.
func (m *GameAccountMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *GameAccountMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the GameAccount entity.
// If the GameAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GameAccountMutation) OldUpdatedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (m *GameAccountMutation) ClearUpdatedAt() {
	m.updated_at = nil
	m.clearedFields[gameaccount.FieldUpdatedAt] = struct{}{}
}

// UpdatedAtCleared returns if the "updated_at" field was cleared in this mutation.
func (m *GameAccountMutation) UpdatedAtCleared() bool {
	_, ok := m.clearedFields[gameaccount.FieldUpdatedAt]
	return ok
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *GameAccountMutation) ResetUpdatedAt() {
	m.updated_at = nil
	delete(m.clearedFields, gameaccount.FieldUpdatedAt)
}

// SetDeletedAt sets the "deleted_at" field.
func (m *GameAccountMutation) SetDeletedAt(t time.Time) {
	m.deleted_at = &t
}

// DeletedAt returns the value of the "deleted_at" field in the mutation.
func (m *GameAccountMutation) DeletedAt() (r time.Time, exists bool) {
	v := m.deleted_at
	if v == nil {
		return
	}
	return *v, true
}

// OldDeletedAt returns the old "deleted_at" field's value of the GameAccount entity.
// If the GameAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GameAccountMutation) OldDeletedAt(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeletedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeletedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeletedAt: %w", err)
	}
	return oldValue.DeletedAt, nil
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (m *GameAccountMutation) ClearDeletedAt() {
	m.deleted_at = nil
	m.clearedFields[gameaccount.FieldDeletedAt] = struct{}{}
}

// DeletedAtCleared returns if the "deleted_at" field was cleared in this mutation.
func (m *GameAccountMutation) DeletedAtCleared() bool {
	_, ok := m.clearedFields[gameaccount.FieldDeletedAt]
	return ok
}

// ResetDeletedAt resets all changes to the "deleted_at" field.
func (m *GameAccountMutation) ResetDeletedAt() {
	m.deleted_at = nil
	delete(m.clearedFields, gameaccount.FieldDeletedAt)
}

// SetTenantID sets the "tenant_id" field.
func (m *GameAccountMutation) SetTenantID(u uint32) {
	m.tenant_id = &u
	m.addtenant_id = nil
}

// TenantID returns the value of the "tenant_id" field in the mutation.
func (m *GameAccountMutation) TenantID() (r uint32, exists bool) {
	v := m.tenant_id
	if v == nil {
		return
	}
	return *v, true
}

// OldTenantID returns the old "tenant_id" field's value of the GameAccount entity.
// If the GameAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GameAccountMutation) OldTenantID(ctx context.Context) (v *uint32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTenantID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTenantID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTenantID: %w", err)
	}
	return oldValue.TenantID, nil
}

// AddTenantID adds u to the "tenant_id" field.
func (m *GameAccountMutation) AddTenantID(u int32) {
	if m.addtenant_id != nil {
		*m.addtenant_id += u
	} else {
		m.addtenant_id = &u
	}
}

// AddedTenantID returns the value that was added to the "tenant_id" field in this mutation.
func (m *GameAccountMutation) AddedTenantID() (r int32, exists bool) {
	v := m.addtenant_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearTenantID clears the value of the "tenant_id" field.
func (m *GameAccountMutation) ClearTenantID() {
	m.tenant_id = nil
	m.addtenant_id = nil
	m.clearedFields[gameaccount.FieldTenantID] = struct{}{}
}

// TenantIDCleared returns if the "tenant_id" field was cleared in this mutation.
func (m *GameAccountMutation) TenantIDCleared() bool {
	_, ok := m.clearedFields[gameaccount.FieldTenantID]
	return ok
}

// ResetTenantID resets all changes to the "tenant_id" field.
func (m *GameAccountMutation) ResetTenantID() {
	m.tenant_id = nil
	m.addtenant_id = nil
	delete(m.clearedFields, gameaccount.FieldTenantID)
}

// SetUserAccount sets the "user_account" field.
func (m *GameAccountMutation) SetUserAccount(s string) {
	m.user_account = &s
}

// UserAccount returns the value of the "user_account" field in the mutation.
func (m *GameAccountMutation) UserAccount() (r string, exists bool) {
	v := m.user_account
	if v == nil {
		return
	}
	return *v, true
}

// OldUserAccount returns the old "user_account" field's value of the GameAccount entity.
// If the GameAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GameAccountMutation) OldUserAccount(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserAccount is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserAccount requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserAccount: %w", err)
	}
	return oldValue.UserAccount, nil
}

// ClearUserAccount clears the value of the "user_account" field.
func (m *GameAccountMutation) ClearUserAccount() {
	m.user_account = nil
	m.clearedFields[gameaccount.FieldUserAccount] = struct{}{}
}

// UserAccountCleared returns if the "user_account" field was cleared in this mutation.
func (m *GameAccountMutation) UserAccountCleared() bool {
	_, ok := m.clearedFields[gameaccount.FieldUserAccount]
	return ok
}

// ResetUserAccount resets all changes to the "user_account" field.
func (m *GameAccountMutation) ResetUserAccount() {
	m.user_account = nil
	delete(m.clearedFields, gameaccount.FieldUserAccount)
}

// SetCredential sets the "credential" field.
func (m *GameAccountMutation) SetCredential(s string) {
	m.credential = &s
}

// Credential returns the value of the "credential" field in the mutation.
func (m *GameAccountMutation) Credential() (r string, exists bool) {
	v := m.credential
	if v == nil {
		return
	}
	return *v, true
}

// OldCredential returns the old "credential" field's value of the GameAccount entity.
// If the GameAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GameAccountMutation) OldCredential(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCredential is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCredential requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCredential: %w", err)
	}
	return oldValue.Credential, nil
}

// ClearCredential clears the value of the "credential" field.
func (m *GameAccountMutation) ClearCredential() {
	m.credential = nil
	m.clearedFields[gameaccount.FieldCredential] = struct{}{}
}

// CredentialCleared returns if the "credential" field was cleared in this mutation.
func (m *GameAccountMutation) CredentialCleared() bool {
	_, ok := m.clearedFields[gameaccount.FieldCredential]
	return ok
}

// ResetCredential resets all changes to the "credential" field.
func (m *GameAccountMutation) ResetCredential() {
	m.credential = nil
	delete(m.clearedFields, gameaccount.FieldCredential)
}

// SetStartTime sets the "start_time" field.
func (m *GameAccountMutation) SetStartTime(t time.Time) {
	m.start_time = &t
}

// StartTime returns the value of the "start_time" field in the mutation.
func (m *GameAccountMutation) StartTime() (r time.Time, exists bool) {
	v := m.start_time
	if v == nil {
		return
	}
	return *v, true
}

// OldStartTime returns the old "start_time" field's value of the GameAccount entity.
// If the GameAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GameAccountMutation) OldStartTime(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStartTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStartTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStartTime: %w", err)
	}
	return oldValue.StartTime, nil
}

// ClearStartTime clears the value of the "start_time" field.
func (m *GameAccountMutation) ClearStartTime() {
	m.start_time = nil
	m.clearedFields[gameaccount.FieldStartTime] = struct{}{}
}

// StartTimeCleared returns if the "start_time" field was cleared in this mutation.
func (m *GameAccountMutation) StartTimeCleared() bool {
	_, ok := m.clearedFields[gameaccount.FieldStartTime]
	return ok
}

// ResetStartTime resets all changes to the "start_time" field.
func (m *GameAccountMutation) ResetStartTime() {
	m.start_time = nil
	delete(m.clearedFields, gameaccount.FieldStartTime)
}

// SetExpireTime sets the "expire_time" field.
func (m *GameAccountMutation) SetExpireTime(t time.Time) {
	m.expire_time = &t
}

// ExpireTime returns the value of the "expire_time" field in the mutation.
func (m *GameAccountMutation) ExpireTime() (r time.Time, exists bool) {
	v := m.expire_time
	if v == nil {
		return
	}
	return *v, true
}

// OldExpireTime returns the old "expire_time" field's value of the GameAccount entity.
// If the GameAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GameAccountMutation) OldExpireTime(ctx context.Context) (v *time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExpireTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExpireTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExpireTime: %w", err)
	}
	return oldValue.ExpireTime, nil
}

// ClearExpireTime clears the value of the "expire_time" field.
func (m *GameAccountMutation) ClearExpireTime() {
	m.expire_time = nil
	m.clearedFields[gameaccount.FieldExpireTime] = struct{}{}
}

// ExpireTimeCleared returns if the "expire_time" field was cleared in this mutation.
func (m *GameAccountMutation) ExpireTimeCleared() bool {
	_, ok := m.clearedFields[gameaccount.FieldExpireTime]
	return ok
}

// ResetExpireTime resets all changes to the "expire_time" field.
func (m *GameAccountMutation) ResetExpireTime() {
	m.expire_time = nil
	delete(m.clearedFields, gameaccount.FieldExpireTime)
}

// SetType sets the "type" field.
func (m *GameAccountMutation) SetType(i int32) {
	m._type = &i
	m.add_type = nil
}

// GetType returns the value of the "type" field in the mutation.
func (m *GameAccountMutation) GetType() (r int32, exists bool) {
	v := m._type
	if v == nil {
		return
	}
	return *v, true
}

// OldType returns the old "type" field's value of the GameAccount entity.
// If the GameAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GameAccountMutation) OldType(ctx context.Context) (v *int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldType: %w", err)
	}
	return oldValue.Type, nil
}

// AddType adds i to the "type" field.
func (m *GameAccountMutation) AddType(i int32) {
	if m.add_type != nil {
		*m.add_type += i
	} else {
		m.add_type = &i
	}
}

// AddedType returns the value that was added to the "type" field in this mutation.
func (m *GameAccountMutation) AddedType() (r int32, exists bool) {
	v := m.add_type
	if v == nil {
		return
	}
	return *v, true
}

// ClearType clears the value of the "type" field.
func (m *GameAccountMutation) ClearType() {
	m._type = nil
	m.add_type = nil
	m.clearedFields[gameaccount.FieldType] = struct{}{}
}

// TypeCleared returns if the "type" field was cleared in this mutation.
func (m *GameAccountMutation) TypeCleared() bool {
	_, ok := m.clearedFields[gameaccount.FieldType]
	return ok
}

// ResetType resets all changes to the "type" field.
func (m *GameAccountMutation) ResetType() {
	m._type = nil
	m.add_type = nil
	delete(m.clearedFields, gameaccount.FieldType)
}

// SetEnabled sets the "enabled" field.
func (m *GameAccountMutation) SetEnabled(b bool) {
	m.enabled = &b
}

// Enabled returns the value of the "enabled" field in the mutation.
func (m *GameAccountMutation) Enabled() (r bool, exists bool) {
	v := m.enabled
	if v == nil {
		return
	}
	return *v, true
}

// OldEnabled returns the old "enabled" field's value of the GameAccount entity.
// If the GameAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GameAccountMutation) OldEnabled(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEnabled is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEnabled requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEnabled: %w", err)
	}
	return oldValue.Enabled, nil
}

// ResetEnabled resets all changes to the "enabled" field.
func (m *GameAccountMutation) ResetEnabled() {
	m.enabled = nil
}

// SetEmulatorID sets the "emulator_id" field.
func (m *GameAccountMutation) SetEmulatorID(i int64) {
	m.emulator_id = &i
	m.addemulator_id = nil
}

// EmulatorID returns the value of the "emulator_id" field in the mutation.
func (m *GameAccountMutation) EmulatorID() (r int64, exists bool) {
	v := m.emulator_id
	if v == nil {
		return
	}
	return *v, true
}

// OldEmulatorID returns the old "emulator_id" field's value of the GameAccount entity.
// If the GameAccount object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *GameAccountMutation) OldEmulatorID(ctx context.Context) (v *int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldEmulatorID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldEmulatorID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldEmulatorID: %w", err)
	}
	return oldValue.EmulatorID, nil
}

// AddEmulatorID adds i to the "emulator_id" field.
func (m *GameAccountMutation) AddEmulatorID(i int64) {
	if m.addemulator_id != nil {
		*m.addemulator_id += i
	} else {
		m.addemulator_id = &i
	}
}

// AddedEmulatorID returns the value that was added to the "emulator_id" field in this mutation.
func (m *GameAccountMutation) AddedEmulatorID() (r int64, exists bool) {
	v := m.addemulator_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearEmulatorID clears the value of the "emulator_id" field.
func (m *GameAccountMutation) ClearEmulatorID() {
	m.emulator_id = nil
	m.addemulator_id = nil
	m.clearedFields[gameaccount.FieldEmulatorID] = struct{}{}
}

// EmulatorIDCleared returns if the "emulator_id" field was cleared in this mutation.
func (m *GameAccountMutation) EmulatorIDCleared() bool {
	_, ok := m.clearedFields[gameaccount.FieldEmulatorID]
	return ok
}

// ResetEmulatorID resets all changes to the "emulator_id" field.
func (m *GameAccountMutation) ResetEmulatorID() {
	m.emulator_id = nil
	m.addemulator_id = nil
	delete(m.clearedFields, gameaccount.FieldEmulatorID)
}

// Where appends a list predicates to the GameAccountMutation builder.
func (m *GameAccountMutation) Where(ps ...predicate.GameAccount) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the GameAccountMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *GameAccountMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.GameAccount, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *GameAccountMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *GameAccountMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (GameAccount).
func (m *GameAccountMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *GameAccountMutation) Fields() []string {
	fields := make([]string, 0, 14)
	if m.created_by != nil {
		fields = append(fields, gameaccount.FieldCreatedBy)
	}
	if m.updated_by != nil {
		fields = append(fields, gameaccount.FieldUpdatedBy)
	}
	if m.deleted_by != nil {
		fields = append(fields, gameaccount.FieldDeletedBy)
	}
	if m.created_at != nil {
		fields = append(fields, gameaccount.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, gameaccount.FieldUpdatedAt)
	}
	if m.deleted_at != nil {
		fields = append(fields, gameaccount.FieldDeletedAt)
	}
	if m.tenant_id != nil {
		fields = append(fields, gameaccount.FieldTenantID)
	}
	if m.user_account != nil {
		fields = append(fields, gameaccount.FieldUserAccount)
	}
	if m.credential != nil {
		fields = append(fields, gameaccount.FieldCredential)
	}
	if m.start_time != nil {
		fields = append(fields, gameaccount.FieldStartTime)
	}
	if m.expire_time != nil {
		fields = append(fields, gameaccount.FieldExpireTime)
	}
	if m._type != nil {
		fields = append(fields, gameaccount.FieldType)
	}
	if m.enabled != nil {
		fields = append(fields, gameaccount.FieldEnabled)
	}
	if m.emulator_id != nil {
		fields = append(fields, gameaccount.FieldEmulatorID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *GameAccountMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case gameaccount.FieldCreatedBy:
		return m.CreatedBy()
	case gameaccount.FieldUpdatedBy:
		return m.UpdatedBy()
	case gameaccount.FieldDeletedBy:
		return m.DeletedBy()
	case gameaccount.FieldCreatedAt:
		return m.CreatedAt()
	case gameaccount.FieldUpdatedAt:
		return m.UpdatedAt()
	case gameaccount.FieldDeletedAt:
		return m.DeletedAt()
	case gameaccount.FieldTenantID:
		return m.TenantID()
	case gameaccount.FieldUserAccount:
		return m.UserAccount()
	case gameaccount.FieldCredential:
		return m.Credential()
	case gameaccount.FieldStartTime:
		return m.StartTime()
	case gameaccount.FieldExpireTime:
		return m.ExpireTime()
	case gameaccount.FieldType:
		return m.GetType()
	case gameaccount.FieldEnabled:
		return m.Enabled()
	case gameaccount.FieldEmulatorID:
		return m.EmulatorID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *GameAccountMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case gameaccount.FieldCreatedBy:
		return m.OldCreatedBy(ctx)
	case gameaccount.FieldUpdatedBy:
		return m.OldUpdatedBy(ctx)
	case gameaccount.FieldDeletedBy:
		return m.OldDeletedBy(ctx)
	case gameaccount.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case gameaccount.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case gameaccount.FieldDeletedAt:
		return m.OldDeletedAt(ctx)
	case gameaccount.FieldTenantID:
		return m.OldTenantID(ctx)
	case gameaccount.FieldUserAccount:
		return m.OldUserAccount(ctx)
	case gameaccount.FieldCredential:
		return m.OldCredential(ctx)
	case gameaccount.FieldStartTime:
		return m.OldStartTime(ctx)
	case gameaccount.FieldExpireTime:
		return m.OldExpireTime(ctx)
	case gameaccount.FieldType:
		return m.OldType(ctx)
	case gameaccount.FieldEnabled:
		return m.OldEnabled(ctx)
	case gameaccount.FieldEmulatorID:
		return m.OldEmulatorID(ctx)
	}
	return nil, fmt.Errorf("unknown GameAccount field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *GameAccountMutation) SetField(name string, value ent.Value) error {
	switch name {
	case gameaccount.FieldCreatedBy:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedBy(v)
		return nil
	case gameaccount.FieldUpdatedBy:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedBy(v)
		return nil
	case gameaccount.FieldDeletedBy:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeletedBy(v)
		return nil
	case gameaccount.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case gameaccount.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case gameaccount.FieldDeletedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeletedAt(v)
		return nil
	case gameaccount.FieldTenantID:
		v, ok := value.(uint32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTenantID(v)
		return nil
	case gameaccount.FieldUserAccount:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserAccount(v)
		return nil
	case gameaccount.FieldCredential:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCredential(v)
		return nil
	case gameaccount.FieldStartTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStartTime(v)
		return nil
	case gameaccount.FieldExpireTime:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExpireTime(v)
		return nil
	case gameaccount.FieldType:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetType(v)
		return nil
	case gameaccount.FieldEnabled:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEnabled(v)
		return nil
	case gameaccount.FieldEmulatorID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetEmulatorID(v)
		return nil
	}
	return fmt.Errorf("unknown GameAccount field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *GameAccountMutation) AddedFields() []string {
	var fields []string
	if m.addcreated_by != nil {
		fields = append(fields, gameaccount.FieldCreatedBy)
	}
	if m.addupdated_by != nil {
		fields = append(fields, gameaccount.FieldUpdatedBy)
	}
	if m.adddeleted_by != nil {
		fields = append(fields, gameaccount.FieldDeletedBy)
	}
	if m.addtenant_id != nil {
		fields = append(fields, gameaccount.FieldTenantID)
	}
	if m.add_type != nil {
		fields = append(fields, gameaccount.FieldType)
	}
	if m.addemulator_id != nil {
		fields = append(fields, gameaccount.FieldEmulatorID)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *GameAccountMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case gameaccount.FieldCreatedBy:
		return m.AddedCreatedBy()
	case gameaccount.FieldUpdatedBy:
		return m.AddedUpdatedBy()
	case gameaccount.FieldDeletedBy:
		return m.AddedDeletedBy()
	case gameaccount.FieldTenantID:
		return m.AddedTenantID()
	case gameaccount.FieldType:
		return m.AddedType()
	case gameaccount.FieldEmulatorID:
		return m.AddedEmulatorID()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *GameAccountMutation) AddField(name string, value ent.Value) error {
	switch name {
	case gameaccount.FieldCreatedBy:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCreatedBy(v)
		return nil
	case gameaccount.FieldUpdatedBy:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUpdatedBy(v)
		return nil
	case gameaccount.FieldDeletedBy:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDeletedBy(v)
		return nil
	case gameaccount.FieldTenantID:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTenantID(v)
		return nil
	case gameaccount.FieldType:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddType(v)
		return nil
	case gameaccount.FieldEmulatorID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddEmulatorID(v)
		return nil
	}
	return fmt.Errorf("unknown GameAccount numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *GameAccountMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(gameaccount.FieldCreatedBy) {
		fields = append(fields, gameaccount.FieldCreatedBy)
	}
	if m.FieldCleared(gameaccount.FieldUpdatedBy) {
		fields = append(fields, gameaccount.FieldUpdatedBy)
	}
	if m.FieldCleared(gameaccount.FieldDeletedBy) {
		fields = append(fields, gameaccount.FieldDeletedBy)
	}
	if m.FieldCleared(gameaccount.FieldCreatedAt) {
		fields = append(fields, gameaccount.FieldCreatedAt)
	}
	if m.FieldCleared(gameaccount.FieldUpdatedAt) {
		fields = append(fields, gameaccount.FieldUpdatedAt)
	}
	if m.FieldCleared(gameaccount.FieldDeletedAt) {
		fields = append(fields, gameaccount.FieldDeletedAt)
	}
	if m.FieldCleared(gameaccount.FieldTenantID) {
		fields = append(fields, gameaccount.FieldTenantID)
	}
	if m.FieldCleared(gameaccount.FieldUserAccount) {
		fields = append(fields, gameaccount.FieldUserAccount)
	}
	if m.FieldCleared(gameaccount.FieldCredential) {
		fields = append(fields, gameaccount.FieldCredential)
	}
	if m.FieldCleared(gameaccount.FieldStartTime) {
		fields = append(fields, gameaccount.FieldStartTime)
	}
	if m.FieldCleared(gameaccount.FieldExpireTime) {
		fields = append(fields, gameaccount.FieldExpireTime)
	}
	if m.FieldCleared(gameaccount.FieldType) {
		fields = append(fields, gameaccount.FieldType)
	}
	if m.FieldCleared(gameaccount.FieldEmulatorID) {
		fields = append(fields, gameaccount.FieldEmulatorID)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *GameAccountMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *GameAccountMutation) ClearField(name string) error {
	switch name {
	case gameaccount.FieldCreatedBy:
		m.ClearCreatedBy()
		return nil
	case gameaccount.FieldUpdatedBy:
		m.ClearUpdatedBy()
		return nil
	case gameaccount.FieldDeletedBy:
		m.ClearDeletedBy()
		return nil
	case gameaccount.FieldCreatedAt:
		m.ClearCreatedAt()
		return nil
	case gameaccount.FieldUpdatedAt:
		m.ClearUpdatedAt()
		return nil
	case gameaccount.FieldDeletedAt:
		m.ClearDeletedAt()
		return nil
	case gameaccount.FieldTenantID:
		m.ClearTenantID()
		return nil
	case gameaccount.FieldUserAccount:
		m.ClearUserAccount()
		return nil
	case gameaccount.FieldCredential:
		m.ClearCredential()
		return nil
	case gameaccount.FieldStartTime:
		m.ClearStartTime()
		return nil
	case gameaccount.FieldExpireTime:
		m.ClearExpireTime()
		return nil
	case gameaccount.FieldType:
		m.ClearType()
		return nil
	case gameaccount.FieldEmulatorID:
		m.ClearEmulatorID()
		return nil
	}
	return fmt.Errorf("unknown GameAccount nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *GameAccountMutation) ResetField(name string) error {
	switch name {
	case gameaccount.FieldCreatedBy:
		m.ResetCreatedBy()
		return nil
	case gameaccount.FieldUpdatedBy:
		m.ResetUpdatedBy()
		return nil
	case gameaccount.FieldDeletedBy:
		m.ResetDeletedBy()
		return nil
	case gameaccount.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case gameaccount.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case gameaccount.FieldDeletedAt:
		m.ResetDeletedAt()
		return nil
	case gameaccount.FieldTenantID:
		m.ResetTenantID()
		return nil
	case gameaccount.FieldUserAccount:
		m.ResetUserAccount()
		return nil
	case gameaccount.FieldCredential:
		m.ResetCredential()
		return nil
	case gameaccount.FieldStartTime:
		m.ResetStartTime()
		return nil
	case gameaccount.FieldExpireTime:
		m.ResetExpireTime()
		return nil
	case gameaccount.FieldType:
		m.ResetType()
		return nil
	case gameaccount.FieldEnabled:
		m.ResetEnabled()
		return nil
	case gameaccount.FieldEmulatorID:
		m.ResetEmulatorID()
		return nil
	}
	return fmt.Errorf("unknown GameAccount field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *GameAccountMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *GameAccountMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *GameAccountMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *GameAccountMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *GameAccountMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *GameAccountMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *GameAccountMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown GameAccount unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *GameAccountMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown GameAccount edge %s", name)
}
