// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
	"go-wind-admin/app/game/service/internal/data"
	"go-wind-admin/app/game/service/internal/server"
	"go-wind-admin/app/game/service/internal/service"
)

import (
	_ "github.com/tx7do/kratos-bootstrap/config/nacos"
	_ "github.com/tx7do/kratos-bootstrap/registry/nacos"
)

// Injectors from wire.go:

func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	gameAccountRepo := data.NewGameAccountRepo(context, entClient)
	gameAccountService := service.NewGameAccountService(context, gameAccountRepo)
	adminClient, err := data.NewAdminClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	testService := service.NewTestService(context, adminClient)
	httpServer, err := server.NewRestServer(context, gameAccountService, testService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(context, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
